name: Hello 

on:
  push:
    branches: [ master ]

jobs:
  weekday_job:
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: Sat
    steps:
      - name: "Hello when it's Saturday"
        if: ${{ env.DAY_OF_WEEK == 'Sat' }}
        run: echo "Hello $FIRST_NAME $Last_Name, today is Saturday!"
      - name: "When it's not a Saturday"  
        env:
          FIRST_NAME: Koryun
          Last_Name: Gevorgyan
      - name: Set current date as env variable
        run: echo " Hello $FIRST_NAME $Last_Name, NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW

 
